# Rossoctl minimal installation configuration with Auth enabled

####################################################################
# rossoctl-deps
####################################################################
gatewayApi:
  enabled: true

certManager:
  enabled: true

tekton:
  enabled: true

charts:
  ####################################################################
  # rossoctl-deps
  ####################################################################
  rossoctl-deps:
    enabled: true
    values:
      openshift: false
      components:
        ingressGateway:
          enabled: true
        containerRegistry:
          enabled: true
        keycloak:
          enabled: true

  ####################################################################
  # rossoctl
  ####################################################################
  rossoctl:
    enabled: true
    values:
      openshift: false
      components:
        agentNamespaces:
          enabled: true
        platformOperator:
          enabled: true
        ui:
          enabled: true
      # configs
      ui:
        auth:
          enabled: true

  ####################################################################
  # istio  - required for the ingress gateway
  ####################################################################
  istio:
    enabled: true

kind_images_preload: false
# docker or podman
container_engine: docker



