# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openshell/v1/exec.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "openshell/v1/exec.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17openshell/v1/exec.proto\x12\x0copenshell.v1"\xfb\x01\n\x12\x45xecSandboxRequest\x12\x12\n\nsandbox_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x03(\t\x12\x0f\n\x07workdir\x18\x03 \x01(\t\x12\x46\n\x0b\x65nvironment\x18\x04 \x03(\x0b\x32\x31.openshell.v1.ExecSandboxRequest.EnvironmentEntry\x12\x17\n\x0ftimeout_seconds\x18\x05 \x01(\r\x12\r\n\x05stdin\x18\x06 \x01(\x0c\x12\x0b\n\x03tty\x18\x07 \x01(\x08\x1a\x32\n\x10\x45nvironmentEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\xb2\x01\n\x10\x45xecSandboxEvent\x12\x31\n\x06stdout\x18\x01 \x01(\x0b\x32\x1f.openshell.v1.ExecSandboxStdoutH\x00\x12\x31\n\x06stderr\x18\x02 \x01(\x0b\x32\x1f.openshell.v1.ExecSandboxStderrH\x00\x12-\n\x04\x65xit\x18\x03 \x01(\x0b\x32\x1d.openshell.v1.ExecSandboxExitH\x00\x42\t\n\x07payload"!\n\x11\x45xecSandboxStdout\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"!\n\x11\x45xecSandboxStderr\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"$\n\x0f\x45xecSandboxExit\x12\x11\n\texit_code\x18\x01 \x01(\x05\x32^\n\tOpenShell\x12Q\n\x0b\x45xecSandbox\x12 .openshell.v1.ExecSandboxRequest\x1a\x1e.openshell.v1.ExecSandboxEvent0\x01\x42\x02P\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "openshell.v1.exec_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"P\001"
    _globals["_EXECSANDBOXREQUEST_ENVIRONMENTENTRY"]._loaded_options = None
    _globals["_EXECSANDBOXREQUEST_ENVIRONMENTENTRY"]._serialized_options = b"8\001"
    _globals["_EXECSANDBOXREQUEST"]._serialized_start = 42
    _globals["_EXECSANDBOXREQUEST"]._serialized_end = 293
    _globals["_EXECSANDBOXREQUEST_ENVIRONMENTENTRY"]._serialized_start = 243
    _globals["_EXECSANDBOXREQUEST_ENVIRONMENTENTRY"]._serialized_end = 293
    _globals["_EXECSANDBOXEVENT"]._serialized_start = 296
    _globals["_EXECSANDBOXEVENT"]._serialized_end = 474
    _globals["_EXECSANDBOXSTDOUT"]._serialized_start = 476
    _globals["_EXECSANDBOXSTDOUT"]._serialized_end = 509
    _globals["_EXECSANDBOXSTDERR"]._serialized_start = 511
    _globals["_EXECSANDBOXSTDERR"]._serialized_end = 544
    _globals["_EXECSANDBOXEXIT"]._serialized_start = 546
    _globals["_EXECSANDBOXEXIT"]._serialized_end = 582
    _globals["_OPENSHELL"]._serialized_start = 584
    _globals["_OPENSHELL"]._serialized_end = 678
# @@protoc_insertion_point(module_scope)
