# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from app.services.openshell.v1 import exec_pb2 as openshell_dot_v1_dot_exec__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in openshell/v1/exec_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class OpenShellStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecSandbox = channel.unary_stream(
            "/openshell.v1.OpenShell/ExecSandbox",
            request_serializer=openshell_dot_v1_dot_exec__pb2.ExecSandboxRequest.SerializeToString,
            response_deserializer=openshell_dot_v1_dot_exec__pb2.ExecSandboxEvent.FromString,
            _registered_method=True,
        )


class OpenShellServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OpenShellServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecSandbox": grpc.unary_stream_rpc_method_handler(
            servicer.ExecSandbox,
            request_deserializer=openshell_dot_v1_dot_exec__pb2.ExecSandboxRequest.FromString,
            response_serializer=openshell_dot_v1_dot_exec__pb2.ExecSandboxEvent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "openshell.v1.OpenShell", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("openshell.v1.OpenShell", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class OpenShell(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecSandbox(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/openshell.v1.OpenShell/ExecSandbox",
            openshell_dot_v1_dot_exec__pb2.ExecSandboxRequest.SerializeToString,
            openshell_dot_v1_dot_exec__pb2.ExecSandboxEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
