{{- if .Values.components.keycloak.enabled }}
# ------------------------------------------------------------------
#  Creates the Namespace for all Keycloak-related resources.
#  This is created during the main install, before any hooks.
# ------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.keycloak.namespace }}
  labels:
    {{- include "rossoctl.labels" . | nindent 4 }}
    istio-discovery: enabled
    shared-gateway-access: "true"
{{- end }}
