apiVersion: v1
kind: ConfigMap
metadata:
  name: app-demo-config
  namespace: rossoctl-system
  labels:
    app: app-demo
data:
  ROSSOCTL_API_URL: "http://rossoctl-backend.rossoctl-system.svc.cluster.local:8000"
  KEYCLOAK_URL: "http://keycloak-service.keycloak.svc.cluster.local:8080"
  KEYCLOAK_PUBLIC_URL: "http://keycloak.localtest.me:8080"
  KEYCLOAK_REALM: "rossoctl"
  CLIENT_ID: "app-demo"
  ENABLE_AUTH: "true"
  DOMAIN_NAME: "localtest.me"
  TOKEN_BROKER_URL: "http://token-broker.rossoctl-demo.svc.cluster.local:8190"
