name: Rossoctl Project Automation

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  add:
    name: Add item to Rossoctl Project

    permissions:
      issues: write
      pull-requests: write
      contents: read

    uses: rossoctl/.github/.github/workflows/add-to-project.yml@99700ebe858a1bc566492b1de9aea6e764ee226f # 2026-05-05
    secrets: inherit
